### ISSUE TITLE
Non numeric value error 

### ISSUE THREAD

**Issue by Dearbhaile** [arq5x/bedtools2#432] opened 2016-08-17 16:55 UTC
I keep getting this error : 

chr1 in 3.NING: Non numeric value 207666.0 

this is clearly a numeric value?

**Comment by Dearbhaile** [comment] 2016-08-17 16:57
I also get this 
file /Users/casey/Documents/Bedfiles/DGV_variant_copy3.bed has non positional records, which are only valid for the groupBy tool.
 and I can't see what is wrong with my file?
Can anyone help.

**Comment by arq5x** [comment] 2016-08-31 19:05
Could you please state the version you are using, the command you invoked, and provide a minimal test file with which I can attempt to reproduce the problem?  Otherwise, it is almost impossible to fathom even a guess.

**Comment by lzamparo** [comment] 2016-09-20 02:05
I'm also seeing the "[bedfile] has non positional records, which are only valid for the groupBy tool."  Not sure if it's the same cause, but here's my reproducible example

> bedtools --version
bedtools v2.25.0

Minimal test file 'a':

> chrom	chromStart	chromEnd	name	score	strand
> chr14	24800000	24810000	blarg	0	.
> chr11	64610000	64620000	blarg	0	.
> chr14	24710000	24720000	blarg	0	.
> chr11	111230000	111240000	blarg	0	.
> 

Minimal test file 'b':

chr1	10000	10600	15_Repetitive/CNV	0	.	10000	10600	245,245,245
chr1	10600	11137	13_Heterochrom/lo	0	.	10600	11137	245,245,245
chr1	11137	11737	8_Insulator	0	.	11137	11737	10,190,254
chr1	11737	11937	11_Weak_Txn	0	.	11737	11937	153,255,102
chr1	11937	12137	7_Weak_Enhancer	0	.	11937	12137	255,252,4

Executing

`bedtools intersect -a file_a.bed -b file_b.bed > first_bins_labeled.bed`

yields the error 

> ERROR: file file_a.bed has non positional records, which are only valid for the groupBy tool.

Any idea what's causing this?  I thought at first it was because my regions in file_a were not stranded, but even with no strand, it doesn't work.

Actually, if I remove the header for my file_a it seems to produce output.  Seems like a bug, or at least a misleading error message.

**Comment by arq5x** [comment] 2016-09-26 19:14
The error message is confusing, sorry. In this case, bedtools could not recognize that the first line in your a file was a header. Therefore it was trying to make sense of "chromStart" as a chromosome coordinate. Prefixing the line with a "#" character fixes this. I have also pushed a fix allowing bedtools to recognize "chrom" and "chr" as valid beginnings of a header line.

**Closed by arq5x** 2016-09-26 19:14 UTC
