### ISSUE TITLE
Memory requirements for intersecting unsorted BED files

### ISSUE THREAD

**Issue by sven0schuierer** [arq5x/bedtools2#232] opened 2015-05-12 09:43 UTC
Hi,

I am using BedTools in an application where it is important to keep the read by read ordering. So I am working with unordered BED files. With BedTools version 2.15.0 I can intersect an (unsorted) BED file with ~194M BED entries with a BED file with ~34M entries using ~14GB of memory. When I use BedTools version 2.23.0 the memory required climbs quickly to >100GB at which time I have to kill the process before it crashes my machine - even if the second BED file with 34M entries is sorted.

The call looks like:

bedtools intersect -wo -a <File 1 with 194M entries> -b <Sorted BED File2 with 34M entries>

Are there any plans to support unsorted BED files in a similar way than was the case in version 2.15.0?

Best regards,

Sven

**Comment by arq5x** [comment] 2015-05-12 12:15
Hi Sven,

The memory usage for the tree-based intersection algorithm has definitely increased, but I am a bit surprised by the degree of the increase in your case. @nkindlon do you have any ideas?

One work around would be assign a line number to your unsorted file, then sort it by chrom/start for the `-sorted` option, then re-sort the output by the line number:

    # test file
    ➜  bedtools2 git:(master) ✗ cat foo.bed
    chr2	10	20
    chr3	15	30
    chr2	40	50
    chr1	10	20
   
    # add a dummy line number and then sort by chrom/start
    ➜  bedtools2 git:(master) ✗ awk '{print $0"\t"NR}' foo.bed | sort -k1,1 -k2,2n > foo.sorted.bed
    
    # intersect, but output is NOT sorted by original line number
    ➜  bedtools2 git:(master) ✗ bedtools intersect -a foo.sorted.bed -b foo.sorted.bed -sorted -wa -wb
    chr1	10	20	4	chr1	10	20	4
    chr2	10	20	1	chr2	10	20	1
    chr2	40	50	3	chr2	40	50	3
    chr3	15	30	2	chr3	15	30	2

    # intersect, and output IS sorted by original line number
    ➜  bedtools2 git:(master) ✗ bedtools intersect -a foo.sorted.bed -b foo.sorted.bed -sorted -wa -wb | sort -k4,4n
    chr2	10	20	1	chr2	10	20	1
    chr3	15	30	2	chr3	15	30	2
    chr2	40	50	3	chr2	40	50	3
    chr1	10	20	4	chr1	10	20	4

**Comment by sven0schuierer** [comment] 2015-05-12 12:26
Hi Aaron,

Thanks a lot for your quick reply and your suggestion. The work-around is definitely an idea I can try out.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-12 15:58
Hi,
    No, I can't think of anything intentional that would cause so massive a spike, so the likely culprit is a memory leak somewhere. I'll try running some tests and see if I can find it.

**Comment by nkindlon** [comment] 2015-05-13 13:21
Hi again,
      Well, I only have 8G on my machine, with no current access to a stronger one, so the largest database I could run was 20M bed records. And that used just over 8G. Experiments with smaller files showed that unsorted intersect in 2.23 does consistently use 25-30% more RAM than 2.15, but definitely not the 7x spike described above. Also, none of the runs showed any memory leaks. 

Not to sound insulting, but is there any chance you accidently swapped your -a and -b files? You mentioned using files with 194M records and 34M records. If the larger one was used as the -b file, 100G of ram is about exactly what I'd expect it to need.

**Comment by sven0schuierer** [comment] 2015-05-13 13:57
Hi Neil,

Thanks a lot for taking a look at this. I know that 90% of the bugs are user errors but I can assure you that I am using bedtools in the way I mentioned. I also assume that BedTools 2.15.0 which works for my case would not be able to handle a 194M BED as the –b argument.

One special feature of the 34M BED file is that it contains a lot different identifiers as it contains BED intervals on the genome, the transcripts, and a custom junction database consisting of about 13M entries.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-13 14:45
Thanks for confirming; sorry that I had to ask. Aaron suggested it may be because your files have a lot of extra fields with long strings that we don't normally use. As such, the handling for that hasn't been heavily tested for leaks and such. Do you think you could take the first million lines of each of your files, and send them to me at nek3d@virginia.edu?

**Comment by sven0schuierer** [comment] 2015-05-18 08:44
Hi Neil,

I do not seem to be able to do this. I keep getting the following error message even if I break down my files into chunks as small as 5Mb:

[cid:image001.png@01D09157.8EDE4CE0]

My IT support is pretty sure that this is a restriction on  your side. Do you have any suggestion how to circumvent this?

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-18 13:07
I can't see your error message, but I think there's some confusion. You don't need any of our tools to get the first X lines, and it sounds like you were trying to use split or the like to break the files into chunks. You don't need to do that either. You can just the use the head command, a standard linux tool that just gives the first x lines of a file. So:
$ head -1000000 yourAfile > a1M.bed
$ head -1000000 yourBfile > b1M.bed

You can then bundle the two 1 million lines files into a gzipped tarball:
$ tar -cvzf myArchive.tar.gz  a1M.bed  b1M.bed

Then send me the myArchive.tar.gz file at nek3d@virginia.edu. Some mailers don't allow gzipped files to go through, but I know it's allowed on our end, so try that first. If yours doesn't allow it, we can try an ftp or dropbox, perhaps.

**Comment by sven0schuierer** [comment] 2015-05-18 18:36
Hi Neil,

Thanks a lot for the suggestions. I actually created two files with the “head” command, one consisting of 1M lines (the first file for option –a) and one consisting of 3M lines (the second file for option –b). Unfortunately, the first file has a size of 71Mb and the second of 189Mb. I wanted to send the file with 3M lines since the memory used by bedtools goes over 100Gb with this file. Since these files are fairly large, I wanted to compress them which led to files of size 11Mb and 26Mb; I tried to send them (and failed). And then I tried “split” as the easiest option and split a tar ball of both files into files of size 5Mb (and failed again).

I also tried to send one of the 5Mb files to my private account which worked without problems. So I firmly believe that my messages are rejected on your side. Here is the error message again:




This is the mail delivery agent at messagelabs.com.



I was unable to deliver your message to the following addresses:



reply+00bd572b0d1abcd08a3a92d5ff51e5f31f8cdaede7ad942392cf00000001116b25

reply@reply.github.com<mailto:reply@reply.github.com>



Reason: 552 5.3.4 Error: message file too big



The message subject was: RE: [bedtools2] Memory requirements for intersecting unsorted BED files (#232) The message date was: Mon, 18 May 2015 08:36:33 +0000 The message identifier was: B1/EB-02785-FA4A9555 The message reference was: server-8.tower-180.messagelabs.com!1431938210!31174399!1



Please do not reply to this email as it is sent from an unattended mailbox.

Please visit www.messagelabs.com/support<http://www.messagelabs.com/support> for more details about this error message and instructions to resolve this issue.



So if I cannot send these files by mail, I think it will be difficult to get them past our firewall. sftp could work, dropbox I have to ask.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-18 18:49
Sorry, a million was exc3essive. Just send me the first 10,000 lines of each file. Nothing else. I don't want to reproduce the 100G blow up, I'm just looking for memory leaks. If they're there, they should show up with smaller samples. So do this:
$ head -10000 aFile > a10K.bed
$ head -10000 bFile > b10K.bed
Then just mail me both files as attachments. You don't have to zip or tar them.

**Comment by sven0schuierer** [comment] 2015-05-19 06:04
Hi Neil,

Okay, here they come.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-19 11:47
Hey Sven, 
    I didn't receive anything. Did it go through on your end?

**Comment by sven0schuierer** [comment] 2015-05-19 11:55
Hi Neil,

Yes, I sent two files with 10k lines at 8am this morning (CEST) and I did not receive any error message about problems with the delivery.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-19 13:03
I'm sorry, I can't find anything in my inbox, spam or trash folder. Let me give you my gmail address. It's nkindlon@gmail.com. Maybe that will work better. Would you mind sending it there please? I'm so sorry about all this hassle.

**Comment by sven0schuierer** [comment] 2015-05-19 13:18
Hi Neil,

I sent the files again. I also sent it to my private email address and I received the mail. So I hope you received it, too.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-19 13:25
Yes, I finally got them. Thanks! I'll take a look now.

**Comment by nkindlon** [comment] 2015-05-19 16:11
Ok, I do see what you're talking about. For these small samples, 2.23 uses 280M, while 2.15 uses only around 20M. Interestingly, there aren't any memory leaks in 2.23, but there are some in 2.15. 

But do I see what's causing the problem. Like you said, your files have tons of different identifiers instead of the usual chromosomes. In 2.15, that wasn't too bad because the "BinTree" structure didn't add much of anything under each chrom until a record was encountered. When I rewrote it, I had it pre-allocate all 37450 bins for every new chromosome it hits. That makes it faster for the kind of large files we typically get, but your use case exposes a major weakness in it. I'll have to think about whether that can be fixed without hurting the typical case, and discuss it with Aaron. Since this is unsorted intersect, I think we're less concerned with the time performance than we used to be, so a more memory efficient solution may be acceptable.

**Comment by sven0schuierer** [comment] 2015-05-20 07:09
Hi Neil,

Thanks a lot for looking into this.

Of course, I would greatly appreciate if a solution could be found that allows me to process my files with the newer BedTools versions but I also understand that you have other restrictions to consider.

Best regards,

Sven

**Comment by sven0schuierer** [comment] 2015-05-21 05:49
Hi Neil,

Just to clarify for myself. From your explanation I conclude that it would not help in my case to artificially sort the files. This was originally proposed by Aaron. I would still have the large number of identifiers leading to the  increase in memory - independent of whether the files are sorted or not. Is this correct?

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-22 15:57
Hi Sven,
    Sorry, was out of the office, just got back. No, you definitely won't have the same problem if you sort the files. Aaron meant that doing so then allows you to run with the -sorted option, which invokes our very low memory "sweep" algorithm. Given how sparsely covered your identifiers/"chromosomes" are, this should use very little memory (as in well under .5 Gb, if memory serves).

**Comment by sven0schuierer** [comment] 2015-05-26 12:08
Hi Neil,

Thanks a lot. Then I’ll try this out.

Best regards,

Sven

**Comment by sven0schuierer** [comment] 2015-05-26 13:03
Hi Neil,

Sorry, to bother you again. This is an error that I get when I intersect the sorted files which is a little bit mysterious to me:

/home/schuisv1/tools/bedtools2-2.23.0/bin/bedtools intersect -sorted -wo -a <sorted BED file derived from SAM file> -b <sorted exon BED file> > <output file>
ERROR: File /home/schuisv1/ngs/RNA-seq-test/Ensembl-human-100-EQP2.0/exon-pipeline-files/bed-files/ensembl_rna_hs_100_combined_exons.bed.sort has inconsistent naming convention for record:
CHR_HG142_HG150_NOVEL_TEST      56210872        56211628        CHR_HG142_HG150_NOVEL_TEST/56210873/56211628/-  0       -

where

  <sorted exon BED file> = /home/schuisv1/ngs/RNA-seq-test/Ensembl-human-100-EQP2.0/exon-pipeline-files/bed-files/ensembl_rna_hs_100_combined_exons.bed.sort

I used

   sort -k1,1 -k2,2n -S 6G

to sort both files.

Best regards,

Sven

**Comment by nkindlon** [comment] 2015-05-26 21:22
Hi Sven,
     I have some good news for you. We'll be putting out a release shortly that both fixes that last error you saw with the sorted files (a bug in 2.23), and will also return the memory usage for unsorted files back to the levels it was at in 2.15. Should take care of your troubles!

**Comment by sven0schuierer** [comment] 2015-05-27 06:00
Hi Neil,

This is, indeed, excellent news. Thanks a lot. This is really great. I’ll keep looking for the new release.

Best regards,

Sven

**Comment by arq5x** [comment] 2015-05-28 10:12
Fixed in 2.24.0

**Closed by arq5x** 2015-05-28 10:12 UTC
