### ISSUE TITLE
Non-writable IO device error when intersecting BAM and BED files

### ISSUE THREAD

**Issue by s1437643** [arq5x/bedtools2#229] opened 2015-05-07 13:57 UTC
I have a sorted BAM file that I want to filter for reads not overlapping regions in a BED file. However, the following error occurs:

```bash
bedtools intersect -a sample.bam -b regions.bed -v > reads.not.in.regions.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
```

I have plenty of space to write the files, and if I do not specify an output file it prints to the console.

**Comment by arq5x** [comment] 2015-05-07 13:59
Odd. Do you have permissions to write to the space?

**Comment by s1437643** [comment] 2015-05-07 14:00
Yes I do, all other bedtools commands, especially intersect, appear to work fine when using BED files

**Comment by nkindlon** [comment] 2015-05-07 14:55
That's odd. Let me see if I can get that error.

**Comment by s1437643** [comment] 2015-05-07 14:58
Two other users have had similar issues in the past: 
* https://code.google.com/p/bedtools/issues/detail?id=125
* https://code.google.com/p/bedtools/issues/detail?id=150

**Comment by arq5x** [comment] 2015-05-07 14:59
Could you tell us what version you are using?  If you are not using 2.23.0, coulr you upgrade and retry? If it persists, could you provide a minimal test file?

**Comment by nkindlon** [comment] 2015-05-07 15:06
Couldn't get the error with the small example I tried. Yes, could you please send your input files to me at nek3d@uva.edu? Thanks. Below is what I tried:

[nek3d@d-128-109-67 data]$ samtools view a.bam 
a1      0       chr1    11      255     10M     *       0       0       *       *
a2      16      chr1    101     255     100M    *       0       0       *       *
[nek3d@d-128-109-67 data]$ 
[nek3d@d-128-109-67 data]$ more b.bed 
chr1    15      25
[nek3d@d-128-109-67 data]$ ~/2.23space/bt2-release/bin/bedtools intersect -a a.bam -b b.bed -v > out.bam
[nek3d@d-128-109-67 data]$ samtools view out.bam
a2      16      chr1    101     255     100M    *       0       0       *       *

**Comment by s1437643** [comment] 2015-05-07 15:23
I am using v2.23.0, I'll send you some sample files which reproduce the problem.

**Comment by nkindlon** [comment] 2015-05-08 13:34
Hi James, I am SO sorry, I gave you the wrong e-mail address. It is nek3d@virginia.edu. I sincerely and profusely apologize for that.

**Comment by nkindlon** [comment] 2015-05-08 15:56
Hi again, 
   Thanks for sending those files. I ran them, but can't reproduce the error. To confirm, you sent me sample.bam and sample.bed. In your first post, the bed file was named regions.bed.  I just want to make sure it was the same file, just with a different name. Thanks.

**Comment by s1437643** [comment] 2015-05-11 09:58
Hello again, yes the files I sent were just samples of the larger ones. The sample files reproduced the problem for me. I've just tried the command on another computer, running the same OS (CentOS 6.6), and it works correctly. I guess I'll spend some time debugging the environment to see what is causing the problem. Sorry to bother you. Thanks!

**Comment by nkindlon** [comment] 2015-05-12 15:02
No, no bother.  Hmm, the exact same OS worked on one machine but not another? My next guess would be to check the compiler versions. I've seen seg faults in the past with one compiler but not another, typically due to an overwritten buffer. So at a command prompt, type:
g++ --version
To see which version of the compiler is installed.

**Comment by s1437643** [comment] 2015-05-13 08:05
My apologies, the OS it works on is not CentOS 6.6 but actually Ubuntu 14.04, running g++ 4.8.2 using bedtools v2.17.0. I updated bedtools to v2.23.0 and it works correctly. The compiler on the CentOS machine is g++ (GCC) 4.4.7. I probably won't be able to upgrade the compiler directly as I do not have root, but shall try a local install of the latest compiler.

**Comment by nkindlon** [comment] 2015-05-13 11:18
Ok, thanks for checking that. When you say you upgraded from 2.17 to 2.23 and it worked, does that mean the original error you were getting went away?

**Comment by s1437643** [comment] 2015-05-13 11:44
No I mean that it worked on both v2.17.0 and v2.23.0 on Ubuntu, but did not work on v2.23.0 on CentOS

**Comment by nkindlon** [comment] 2015-05-13 12:14
Thanks. I'm using gcc 4.8.3 - I'll try downgrading to 4.4x and see if it errors then. My OS is Red Hat 4.8.2-1, so if that gets the error, we'll know it's compiler dependent. If not, it's OS dependent.

**Comment by nkindlon** [comment] 2015-05-14 20:05
Hi James, I was finally able to get gcc-4.4.7 installed. Unfortunately, the problem still doesn't show up. This is on a machine with Red Hat 4.8.2-1. Did the problem go away when you upgraded the compiler on the CentOS machine? If not, I'm afraid there isn't too much else I can do on my end.

**Comment by arq5x** [comment] 2015-05-18 03:04
Closing, as this appears to not be reproducible. Please reopen if proven otherwise!

**Closed by arq5x** 2015-05-18 03:04 UTC

**Comment by yoonkihoon** [comment] 2015-07-24 17:47
Hi Aron,
This happened to me as well. My OS is Red Hat Enterprise Linux Server release 6.6. When I pipe output from sambamba view to bedtools, the same error occurred. Could you look into this?

sambamba view -f bam -L NA12878-5-noanalysis_blocks.bed NA12878-5/5_130327_iplat-sort.bam | bedtools intersect -abam - -b NA12878-5-noanalysis_blocks.bed -f 1.0 -nonamecheck > 5_130327_iplat-sort-noanalysis-prep.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
Aborted

If I piped into samtools, the it is perfectly OK.
sambamba view -f bam -L NA12878-5-noanalysis_blocks.bed NA12878-5/5_130327_iplat-sort.bam | samtools view - | head -n 4
ERR091571.70803150      163     1       16821821        0       101M    =    16822096 376     GATTCCTCTTAGGAATATGGCTAAAAGCCGTTTCCCAGACTCCCTTGCAGTCAGATACGGCCATGTGGTCAAGTTCTGGTCCATAGAATTAAGACAGAAAG ?B@D;?DDFFDHDCFHGGGGGIJJJIEEE):1C9:CHIIJJGIIEHI@BDHFGG@GGIHDGEBA?HCEC?DB>DDEDA;AC>@>CCCCCA::(:>A(:AC: NM:i:1  MD:Z:29A71    AS:i:96 XS:i:96 RG:Z:5  XA:Z:1,-17244430,101M,1;

Or, the below command is completely ok as well.
sambamba view -f bam -L NA12878-5-noanalysis_blocks.bed NA12878-5/5_130327_iplat-sort.bam | samtools view - > test.txt

Thanks!!

**Comment by s1437643** [comment] 2015-11-05 16:09
Hello again, I'm still unable to output results in BAM format. Below is a very simple example which fails:

$ cat temp.bed 
chr1	10068	10118	HISEQ:127:C7HJ7ANXX:1:1312:20025:49343/2	30	+
chr1	10074	10124	HISEQ:127:C7HJ7ANXX:1:1312:20025:49343/1	30	-
chr1	10163	10213	HISEQ:127:C7HJ7ANXX:1:1313:9157:25504/1	30	+

$ bedtools bedtobam -i temp.bed -g hg38.txt > tmp.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
Aborted

If I run the command without directing to a file it prints the compressed BAM contents to the screen. I have access to write to the file system and every other command in bedtools works except trying to do intersections with BAM files (as was the original issue).

I compiled bedtools with gcc version 5.2.0 and I'm running on CentOS release 6.7

**Comment by rekado** [comment] 2017-11-19 18:50
I encountered this error with bedtools 2.17 and 2.18 (didn't try later versions).

It only happens when writing to the NFS-mounted home directory, but not when writing to a local disk or a tmpfs, e.g. to /tmp.

**Comment by emham** [comment] 2018-05-16 01:36
@rekado thanks for this - I was having this error as well when writing to an NFS-mounted drive. can write to /tmp without error. not sure why this is.

**Comment by yo54233154** [comment] 2018-08-20 01:39
Same problem here, cannot directly output bam to NFS storage, only bed. Local storage is fine.
My current workaround is pipe to stdout and then use samtools view.

**Comment by luyoutao** [comment] 2019-11-14 15:14
The problem still exists in version 2.26.

**Comment by q2justin** [comment] 2022-10-03 17:26
I just experienced this, but only when utilizing NFS v4. Switching to v3 solves the issue.
