### ISSUE TITLE
error in the 'bedtools merge' output

### ISSUE THREAD

**Issue by matrs** [arq5x/bedtools2#402] opened 2016-05-06 07:54 UTC
bedtools v2.20.1
bedtools v2.25.0

I'm merging a file and I found a bug in the output created by `bedtools merge`

`bedtools merge -i bedtools_sort_10000.txt -c 7,11,13 -o distinct > G1_10000_beds.txt`

what is happening is that some lines in a particular column of the output are composed of 2 numbers separated by a "," , pattern which isn't in the input file and it shouldn't be in the output either.

```
awk '/[0-9]+,[0-9]+/ {print $0}' bedtools_sort_10000.txt |wc -l
0
awk '/[0-9]+,[0-9]+/ {print $0}' G1_10000_beds.txt |wc -l
8
```

I put together a small file to reproduce this problem. Also I attach the output file that contains the error (G1_10000_beds.txt )
https://drive.google.com/file/d/0B1KvVDBRb-fGQlpEb1hhUkZXVzQ/view?usp=sharing
https://drive.google.com/file/d/0B1KvVDBRb-fGWnY1WjZfWmdiUTg/view?usp=sharing

**Comment by arq5x** [comment] 2016-05-06 15:53
I apologize, but I am not sure what the problem is. The `distinct` operator prints a comma-delimited list of the distinct (unique) set of values observed among the records that were merged. I think that is what the output is showing:

```head -n 7 bedtools_sort_10000.txt
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10662	10674	MA0813.1	7.72131	+
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10662	10674	MA0815.1	8.31579	+
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10662	10674	MA0815.1	8.4386	-
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10662	10674	MA0872.1	8.78689	-
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10662	10674	MA0872.1	8.93443	+
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10665	10675	MA0506.1	18.0185	-
chr1	10667	10667	group1	0.014254	0.440192	-0.871722	chr1	10666	10676	MA0506.1	18	+

bedtools merge -i <(head -n 7 bedtools_sort_10000.txt) -c 7,11,13 -o distinct
chr1	10666	10668	-0.871722	MA0506.1,MA0813.1,MA0815.1,MA0872.1	+,-```


Also, do you mean to have zero-length records in your input? Please note that BED format uses 0-based starts and 1-based ends, so for instance, the first nucleotide of chr1 is `chr:0-1`.

**Comment by matrs** [comment] 2016-05-06 18:07
I meant to have 1 base length features, and it works, bedtools intersect and closest understands it. I know that about the BED format f but i haven't changed them yet.

If you run the awk command that i posted you should see what the problem is, maybe I should mentioned that the problem is in the column four, which has to have a single number, not two numbers separated by a comma as in a few lines happen.

As you pointed out the output should be like this :
`chr1    10666   10668   -0.871722   MA0506.1,MA0813.1,MA0815.1,MA0872.1 +,-

And it is like that in most of the lines but not in every line. In the example provided, 8 lines have in the  fourth column two numbers separated by a ",". like this:

```
awk '/[0-9]+,[0-9]+/ {print $4}' G1_10000_beds.txt

1.15435,1.69087
1.37824,1.39867
0.905856,1.09595
0.547446,0.991253
0.651038,1.80181
-0.937445,1.08065
0.531805,0.695807
0.712193,1.04529
```
I discovered this because I wanted to plot that column and my script complained about some values in column 4 aren't a single number so i checked it. The distinct option should put in the column  five those strings `MA0506.1,MA0813.1,MA0815.1,MA0872.1   separated by a comma, not the numbers in column four.


`

**Comment by arq5x** [comment] 2016-05-06 18:16
The problem is arising from using zero-length intervals. For example, here are the 4 records from your input that cause the `1.15435,1.69087` output from your awk command:

```
chr1	1228428	1228428	chr1	1228428	1228428	group1	0.0157281	-0.363099	1.15435	chr1	1228421	1228432	MA0131.2	11.9846	-
chr1	1228428	1228428	chr1	1228428	1228428	group1	0.0157281	-0.363099	1.15435	chr1	1228423	1228433	MA0059.1	9.62887	+
chr1	1228430	1228430	chr1	1228430	1228430	group1	0.00143932	-1.23466	1.69087	chr1	1228421	1228432	MA0131.2	11.9846	-
chr1	1228430	1228430	chr1	1228430	1228430	group1	0.00143932	-1.23466	1.69087	chr1	1228423	1228433	MA0059.1	9.62887	+
```
Because you represent them as 1-based, closed intervals instead of zero-length, half-open (https://www.biostars.org/p/84686/), bedtools is interpreting these coordinates as _insertions_ which efach affect the flanking nucleotide on either side of the insertion. This causes the  (1228428 and 1228430) records to be merged. If you change all of your data to proper BED format (zero-based, half open: `awk -v OFS="\t" '{$2=$2-1; print $0}' bedtools_sort_10000.txt`) your problem should disappear. I tested it and it works for me:

    bedtools merge -i <(awk -v OFS="\t" '{$2=$2-1; print $0}' bedtools_sort_10000.txt) -c 7,11,13 -o distinct | awk '/[0-9]+,[0-9]+/ {print $0}'

**Comment by matrs** [comment] 2016-05-06 19:44
You are right, i will make proper BED files. Sorry for bothering, i didn't see how that could affect the merge process and the output in that way,  so I was sure that I found a bug. Thank you.

**Closed** 2016-05-07 16:35 UTC
