### ISSUE TITLE
bedtools complement unexpected output?

### ISSUE THREAD

**Issue by isthisthat** [arq5x/bedtools2#356] opened 2016-02-04 12:29 UTC
Here is a snippet of my call (human, hg19):

    bedtools complement -i <(echo -e "chr1\t0\t10000\ttelomere") -g <(echo -e "chr1\t249250621")

which gives:

    chr1    0       0
    chr1    10001   249250620

I would expect the following:

    chr1    10000   249250621

The chr1 size is taken from `mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e 
        "select chrom, size from hg19.chromInfo"  > hg19.genome`
which is in the `bedtools coverage` help screen.
I'm using the latest version (v2.25.0)

**Comment by arq5x** [comment] 2016-02-04 14:14
Thanks for reporting this. It looks like there was a regression in one of the recent releases. I will fix this asap.

**Comment by isthisthat** [comment] 2016-02-04 15:11
Thanks a lot. Perhaps also a good test case for your testing framework.

**Comment by isthisthat** [comment] 2016-02-16 11:54
Hello, have there been any updates on this?

**Comment by arq5x** [comment] 2016-02-16 14:25
Yes, I have a fix locally but haven't written all of the necessary tests. I will hopefully push tonight.

**Comment by arq5x** [comment] 2016-02-16 17:14
Just pushed a fix for this with tests. Thanks very much for reporting and for your patience.

**Closed by arq5x** 2016-02-16 17:14 UTC

**Comment by isthisthat** [comment] 2016-02-17 11:24
Thanks for the fix! Confirmed that it works. Looking forward to the next release!
