### ISSUE TITLE
intersect -c option leads to failure

### ISSUE THREAD

**Issue by sarah-thibault** [arq5x/bedtools2#362] opened 2016-02-12 16:35 UTC
hello!

whenever I try to use the intersect -c option bedtools 2.25.0 fails for some unknown reason.  any other flag works and the files work with any other intersect commands.  

bedtools intersect -a file1.bed -b file2.bed -c > file3with#ofhits.bed

thanks for any help or advice!

**Comment by arq5x** [comment] 2016-02-16 16:11
I am unable to reproduce this. could you provide an example of the files you are using that cause this?

**Comment by arq5x** [comment] 2016-02-23 20:24
Closing, as unable to reproduce.

**Closed by arq5x** 2016-02-23 20:24 UTC
