### ISSUE TITLE
Bedtools intersect, problems tabs in compressed format

### ISSUE THREAD

**Issue by jaime11** [arq5x/bedtools2#513] opened 2017-03-30 14:58 UTC
Hello,

I am getting the following error when intersecting (bedtools intersect -v) one compressed bed file with two bed files (one compressed and one uncompressed):

_Error: line number 401105 of file file.bed.gz has 2 fields, but 9 were expected._

I am running the following command:

_bedtools intersect -v -a file.bed.gz -b excl1.bed.gz excl2.bed  | gzip -c > result.bed.gz_

I have verified that uncompressing the input file and piping it through works:

_zcat file.bed.gz | bedtools intersect -v -a stdin -b excl1.bed.gz excl2.bed  | gzip -c > result.bed.gz_

So I am guessing there is an error with the decompression.
Also, if I try to split the fields with awk, I get the correct fields (for example, printing field 4) lines 401091-Peak_401110:

zcat file.bed.gz | head -n 401110 | tail -n 20 | awk 'BEGIN{OFS="\t"}{print $4}'
Peak_401091
Peak_401092
Peak_401093
Peak_401094
Peak_401095
Peak_401096
Peak_401097
Peak_401098
Peak_401099
Peak_401100
Peak_401101
Peak_401102
Peak_401103
Peak_401104
Peak_401105
Peak_401106
Peak_401107
Peak_401108
Peak_401109
Peak_401110

The format of the files:

**file.bed.gz** (tab separated)

chr17   22521249        22521679        Peak_1  19039   .       21.71835        1910.90295      1903.98853
chr3    93470259        93470901        Peak_2  7275    .       15.30395        733.71094       727.53760

**excl1.bed.gz**

chr10   38528030        38529790
chr10   42070420        42070660

**excl2.bed**

chr1    10468   11447   TAR1    1000    .
chr1    629083  634924  chrM    1000    .

I am attaching the files (compressing the excl2.bed)
[excl2.bed.gz](https://github.com/arq5x/bedtools2/files/882815/excl2.bed.gz)
.

Thanks!
[file.bed.gz](https://github.com/arq5x/bedtools2/files/882807/file.bed.gz)

[excl1.bed.gz](https://github.com/arq5x/bedtools2/files/882808/excl1.bed.gz)

**Comment by ghuls** [comment] 2017-04-24 18:04
Do you know how you generated file.bed.gz?

After decompressing and recompressing **file.bed.gz** it works for me.

As far as I could debug it now, is that when reading your **file.bed.gz**, we get EOF before the actual EOF. After playing a bit with the bedtools code, I can get it so it stops at a different location in the file, but it still does not read the file correctly.

**Comment by jaime11** [comment] 2017-04-24 18:09
I recall it must have been generated with a piped command, something along the lines

input_stream | gzip -c > outfile.bed.gz

**Comment by chrarnold** [comment] 2018-07-02 21:35
I am facing the same problem also again. It seems to be a rare phenomenon, and I am wondering where the origin is. Only bedtools seems to have a problem with the file. De- and recompressing helps, but some of my pipelines break because of this. I could provide an example file that causes this issue. Any help is greatly appreciated, I suspect this to be a bug of either bedtools or an upstream tool.

**Comment by chrarnold** [comment] 2018-07-12 13:03
This can be marked as duplicate of issue #643

**Comment by jmarshall** [comment] 2018-07-12 16:07
Confirmed that @jaime11's files exhibit the same problem and are processed correctly with the fix.

Alas, I tried to reproduce the reports here ten days ago, but was running them on macOS — whose `realloc(0)` responds differently so the files were correctly processed.

**Comment by arq5x** [comment] 2018-07-12 16:12
Thanks @jmarshall ! I think that explains my inability to reproduce as well.

**Closed** 2019-08-17 22:39 UTC
