### ISSUE TITLE
Jaccard analysis segmentation fault

### ISSUE THREAD

**Issue by Clockris** [arq5x/bedtools2#779] opened 2019-10-23 15:30 UTC
Hi,

I am trying to do some analysis using the command 

`bedtools jaccard -a $file1 -b $file2`

but for some reason Bedtools crash giving me as error "Segmentation fault (core dumped)".

When I try to run

`bedtools jaccard -a $file1 -b $file3`

and 

`bedtools jaccard -a $file2 -b $file3`

the command works but with 

`bedtools jaccard -a $file3 -b $file2`

it give me segmentation fault again. 

It works even if I run

`bedtools jaccard -a $file2 -b $file1`

The problem seems to be the file2, but it is wired that when it is in the -b position the program works fine and by the way I didn't find any problematic feature in that file that could justify a crash. Do you have any idea about this problem?

Thanks.

Attached there are the files to make the tests.

file1=H3K27ac_ENCSR763IDK_bin100_gap0_peaks.bed.txt
file2=H3K36me3_ENCSR499FXI_bin100_gap0_peaks.bed.txt
file3=H3K4me1_ENCSR155XVP_bin100_gap0_peaks.bed.txt

[H3K4me1_ENCSR155XVP_bin100_gap0_peaks.bed.txt](https://github.com/arq5x/bedtools2/files/3763143/H3K4me1_ENCSR155XVP_bin100_gap0_peaks.bed.txt)
[H3K27ac_ENCSR763IDK_bin100_gap0_peaks.bed.txt](https://github.com/arq5x/bedtools2/files/3763144/H3K27ac_ENCSR763IDK_bin100_gap0_peaks.bed.txt)
[H3K36me3_ENCSR499FXI_bin100_gap0_peaks.bed.txt](https://github.com/arq5x/bedtools2/files/3763145/H3K36me3_ENCSR499FXI_bin100_gap0_peaks.bed.txt)

PS I am working with version 2.29.0 of bedtools on a SGE server using RedHas as OS.

**Comment by 38** [comment] 2019-10-23 18:10
This is caused by access previously allocated memory.

I should make the fix in PR #780. @arq5x, would you like to have a look ?

**Comment by arq5x** [comment] 2019-10-24 19:17
This is fixed in master and a new test has been added. Thanks for reporting it and thanks to @38 for fixing it!

**Closed** 2019-10-24 19:24 UTC

**Comment by Clockris** [comment] 2019-10-25 07:05
I tried the fixed version, it works fine, thanks.
